language: python
sudo: true
python:
  - "3.5"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  - pip3 install PyQt5
  - sudo apt-get install -qq libegl1-mesa

script:
  # so to help eventual debug: knowing what exact versions are in use can be rather useful.
  - pip freeze
  # Code static analysis
  - pep8 --max-line-length=100 --exclude='*.pyc, *.cfg, *.log' --ignore='E402' alignak_app/*
  - pylint --rcfile=.pylintrc alignak_app/
  # - cd test
  - coverage erase
  #- cd test/
  - nosetests -xv --nologcapture --with-coverage --cover-package=alignak_app *.py
  - ls -la
  - coverage combine
  - cat .coverage
  #- cd ..
  - coverage report -m

after_success:
  - coveralls -v
branches:
  only:
    - master
